CLIP_LABEL_MAP = {
    0: "Apple leaf with Apple scab",
    1: "Apple leaf with Black rot",
    2: "Apple leaf with Cedar apple rust",
    3: "Healthy Apple leaf",
    4: "Corn leaf with Cercospora leaf spot (Gray leaf spot)",
    5: "Corn leaf with Common rust",
    6: "Corn leaf with Northern Leaf Blight",
    7: "Healthy Corn leaf",
    8: "Durian leaf with Algal Leaf Spot",
    9: "Durian leaf with Leaf Blight",
    10: "Durian leaf with Leaf Spot",
    11: "Healthy Durian leaf",
    12: "Grape leaf with Black rot",
    13: "Grape leaf with Esca (Black Measles)",
    14: "Grape leaf with Leaf blight (Isariopsis Leaf Spot)",
    15: "Healthy Grape leaf",
    16: "Oil Palm leaf with brown spots",
    17: "Healthy Oil Palm leaf",
    18: "Oil Palm leaf with white scale",
    19: "Orange leaf with Huanglongbing (Citrus greening)",
    20: "Pepper bell leaf with Bacterial spot",
    21: "Healthy Pepper bell leaf",
    22: "Potato leaf with Early blight",
    23: "Potato leaf with Late blight",
    24: "Healthy Potato leaf",
    25: "Rice leaf with Bacterial blight",
    26: "Rice leaf with Blast",
    27: "Rice leaf with Brown spot",
    28: "Rice leaf with Tungro",
    29: "Healthy Soybean leaf",
    30: "Strawberry leaf with Leaf scorch",
    31: "Healthy Strawberry leaf",
    32: "Tomato leaf with Bacterial spot",
    33: "Tomato leaf with Early blight",
    34: "Tomato leaf with Late blight",
    35: "Tomato leaf with Leaf Mold",
    36: "Tomato leaf with Septoria leaf spot",
    37: "Tomato leaf with Spider mites (Two-spotted spider mite)",
    38: "Tomato leaf with Target Spot",
    39: "Tomato leaf with Tomato Yellow Leaf Curl Virus",
    40: "Tomato leaf with Tomato mosaic virus",
    41: "Healthy Tomato leaf"
}
