DISEASE_LABELS = [
    "Apple leaf with Apple scab",
    "Apple leaf with Black rot",
    "Apple leaf with Cedar apple rust",
    "Healthy Apple leaf",
    # "Corn leaf with Cercospora leaf spot (Gray leaf spot)",
    # "Corn leaf with Common rust",
    # "Corn leaf with Northern Leaf Blight",
    # "Healthy Corn leaf",
    # "Durian leaf with Algal Leaf Spot",
    # "Durian leaf with Leaf Blight",
    # "Durian leaf with Leaf Spot",
    # "Healthy Durian leaf",
    "Grape leaf with Black rot",
    "Grape leaf with Esca (Black Measles)",
    "Grape leaf with Leaf blight (Isariopsis Leaf Spot)",
    "Healthy Grape leaf",
    # "Oil Palm leaf with brown spots",
    # "Healthy Oil Palm leaf",
    # "Oil Palm leaf with white scale",
    "Orange leaf with Huanglongbing (Citrus greening)",
    "Pepper bell leaf with Bacterial spot",
    "Healthy Pepper bell leaf",
    "Potato leaf with Early blight",
    "Potato leaf with Late blight",
    "Healthy Potato leaf",
    # "Rice leaf with Bacterial blight",
    # "Rice leaf with Blast",
    # "Rice leaf with Brown spot",
    # "Rice leaf with Tungro",
    "Healthy Soybean leaf",
    "Strawberry leaf with Leaf scorch",
    "Healthy Strawberry leaf",
    "Tomato leaf with Bacterial spot",
    "Tomato leaf with Early blight",
    "Tomato leaf with Late blight",
    "Tomato leaf with Leaf Mold",
    "Tomato leaf with Septoria leaf spot",
    "Tomato leaf with Spider mites (Two-spotted spider mite)",
    "Tomato leaf with Target Spot",
    "Tomato leaf with Tomato Yellow Leaf Curl Virus",
    "Tomato leaf with Tomato mosaic virus",
    "Healthy Tomato leaf",
]

INSECT_LABELS = [
    "Ladybug",
    "Aphid",
    "Whitefly", 
    "Caterpillar", 
    "Spider Mite", 
    "Japanese Beetle", 
    "Beneficial Insect", 
    "Ant", 
    "Snail", 
    "Slug", 
    "Bee", 
    "Wasp"
]

RESNET_TO_CLIP = {
    "Apple Apple scab":                                   "Apple leaf with Apple scab",
    "Apple Black rot":                                    "Apple leaf with Black rot",
    "Apple Cedar apple rust":                             "Apple leaf with Cedar apple rust",
    "Apple healthy":                                      "Healthy Apple leaf",
    "Corn (maize) Cercospora leaf spot Gray leaf spot":   "Corn leaf with Cercospora leaf spot (Gray leaf spot)",
    "Corn (maize) Common rust ":                          "Corn leaf with Common rust",
    "Corn (maize) Northern Leaf Blight":                  "Corn leaf with Northern Leaf Blight",
    "Corn (maize) healthy":                               "Healthy Corn leaf",
    "Grape Black rot":                                    "Grape leaf with Black rot",
    "Grape Esca (Black Measles)":                         "Grape leaf with Esca (Black Measles)",
    "Grape Leaf blight (Isariopsis Leaf Spot)":           "Grape leaf with Leaf blight (Isariopsis Leaf Spot)",
    "Grape healthy":                                      "Healthy Grape leaf",
    "Orange Haunglongbing (Citrus greening)":             "Orange leaf with Huanglongbing (Citrus greening)",
    "Pepper, bell Bacterial spot":                        "Pepper bell leaf with Bacterial spot",
    "Pepper, bell healthy":                               "Healthy Pepper bell leaf",
    "Potato Early blight":                                "Potato leaf with Early blight",
    "Potato Late blight":                                 "Potato leaf with Late blight",
    "Potato healthy":                                     "Healthy Potato leaf",
    "Soybean healthy":                                    "Healthy Soybean leaf",
    "Strawberry Leaf scorch":                             "Strawberry leaf with Leaf scorch",
    "Strawberry healthy":                                 "Healthy Strawberry leaf",
    "Tomato Bacterial spot":                              "Tomato leaf with Bacterial spot",
    "Tomato Early blight":                                "Tomato leaf with Early blight",
    "Tomato Late blight":                                 "Tomato leaf with Late blight",
    "Tomato Leaf Mold":                                   "Tomato leaf with Leaf Mold",
    "Tomato Septoria leaf spot":                          "Tomato leaf with Septoria leaf spot",
    "Tomato Spider mites Two-spotted spider mite":        "Tomato leaf with Spider mites (Two-spotted spider mite)",
    "Tomato Target Spot":                                 "Tomato leaf with Target Spot",
    "Tomato Tomato Yellow Leaf Curl Virus":               "Tomato leaf with Tomato Yellow Leaf Curl Virus",
    "Tomato Tomato mosaic virus":                         "Tomato leaf with Tomato mosaic virus",
    "Tomato healthy":                                     "Healthy Tomato leaf",
}